name: Docker Build and Push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
     

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker image
        run: |
          docker build -t my-python-app1:latest .
          docker tag my-python-app1:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app1:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-python-app1:latest
